tue-robotics/action_server

CMakeLists.txt, package.xml, src/action_server/command_center/actions.py, src/action_server/command_center/command_center.py, src/action_server/command_center/command_recognizer.py
Also remove one unused import.
See https://github.com/tue-robotics/grammar_parser
=> Reuse grammar_parser in action_server

src/action_server/actions/look_at.py
Entity pose is a kdl frame. You should take the vector with .p before putting it in a VectorStamped.
=> fix(look_at): take position vector from entity pose

src/action_server/actions/util/entities_from_description.py, src/action_server/command_center/find_person.py
Relates to https://github.com/tue-robotics/tue_robocup/pull/218
=> self._robot.base.get_location() now returns a FrameStamped (in /map)

src/action_server/actions/find.py
Related to https://github.com/tue-robotics/tue_robocup/issues/258
=> Interpret Entity.pose as FrameStamped in Find action

src/action_server/actions/pick_up.py, src/action_server/actions/util/entities_from_description.py
=> fix(pick-up): grasp if object known, try to find if unknown

src/action_server/actions/pick_up.py
=> fix(pick-up): resulting knowledge gives picking arm

src/action_server/actions/bring.py
If no handover is detected, the gripper wil open anyway after the robot says "here you go". Fixes #17
=> fix(bring): on handover, move the arm to handover pose

src/action_server/actions/demo_presentation.py
Adds the optional language parameter and passes it to the state machine constructor.
=> feat(demo_presentation): add language param

action_server/src/action_server/actions/find.py
=> fix(find): always go find in given location

src/action_server/client.py
part 1 :-)
part 2: https://github.com/tue-robotics/nl_robot_console/pull/20
=> added cancel_all method to send cancel request to simple action server

action_server/src/action_server/actions/find.py
Fixes #85. Reproduced and fix tested in simulation
=> fix(find): dont try to get an entity from the wm without looking

action_server/src/action_server/server.py
=> log(server): add task recipe to stack trace

action_server/src/action_server/actions/demo_presentation.py
=> fix presentation hero

action_server/src/action_server/actions/find.py
Merge together with tue-robotics/tue_robocup#888
=> New find API

action_server/src/action_server/actions/place.py
I changed the input to the place smach state so that it sends an entitydesignator rather than an emptyspotdesignator. This way the smachstate will perform an inspect of the entity before placing
=> Place action input to the smach state

action_server/src/action_server/actions/find.py
Merge together with https://github.com/tue-robotics/tue_robocup/pull/1100
=> Migrate to tf2

action_server/package.xml, action_server/src/action_server/actions/find.py, action_server/src/action_server/actions/look_at.py, action_server/src/action_server/actions/util/entities_from_description.py
Merge after https://github.com/tue-robotics/pykdl_ros/pull/2
=> Apply pykdl_ros

action_server/package.xml, action_server/src/action_server/actions/count_and_tell.py, action_server/src/action_server/actions/example_action.py, action_server/src/action_server/actions/find.py, action_server/src/action_server/actions/follow.py, action_server/src/action_server/actions/guide.py, action_server/src/action_server/actions/guide_final_challenge.py, action_server/src/action_server/actions/hand_over.py, action_server/src/action_server/actions/inspect_action.py, action_server/src/action_server/actions/navigate_to.py, action_server/src/action_server/actions/pick_up.py, action_server/src/action_server/actions/place.py, action_server/src/action_server/actions/util/entities_from_description.py, action_server/test/test_grammar_test.py
Merge together with https://github.com/tue-robotics/tue_robocup/pull/1147
=> Apply ed_python

action_server/src/action_server/actions/point_target.py
This fixes the CI of challenge_demo
=> Fix changed smach_state API

action_server/CMakeLists.txt, action_server_msgs/CMakeLists.txt
Lower minimum cmake requirement is not supported anymore
=> Bump min cmake version to 3.5
